[package]
name = "gll"
version = "0.0.2"
authors = [
    "Ana-Maria <mihalacheana.maria@yahoo.com>",
    "Eduard-Mihai Burtescu <edy.burt@gmail.com>"
]
repository = "https://github.com/lykenware/gll"
license = "MIT/Apache-2.0"
keywords = ["grammar", "generator", "GLL", "parser"]
readme = "README.md"
description = "GLL parsing framework."
edition = "2018"

[dependencies]
indexing = "0.3.1"
indexmap = "1"
grammer = "0.0.1"
proc-macro2 = "0.4.0"
proc-quote = "0.2.0"

[build-dependencies]
indexing = "0.3.1"
indexmap = "1"
grammer = "0.0.1"
proc-macro2 = "0.4.0"
proc-quote = "0.2.0"

[lib]
doctest = false
test = false

[patch.'crates-io']
grammer = { git = "https://github.com/lykenware/grammer", rev = "ed4fc4f9be9aa2c1a6c3245ba4e91684ddff5f2f" }

[workspace]
members = [
    "macros"
]
