[package]
name = "gll"
version = "0.1.0"
authors = [
    "Ana-Maria <mihalacheana.maria@yahoo.com>",
    "Eduard-Mihai Burtescu <edy.burt@gmail.com>"
]
repository = "https://github.com/lykenware/gll"
license = "MIT/Apache-2.0"
description = "GLL parser generator."

[dependencies]
indexing = "0.3.1"
ordermap = "0.3.0"
proc-macro2 = "0.4.0"

[build-dependencies]
indexing = "0.3.1"
ordermap = "0.3.0"

[lib]
doctest = false
test = false

[workspace]
members = [
    "macros"
]
